
// user
export const LOGIN_USER = "LOGIN_USER";

//jobs
export const RECEIVE_JOBS = "RECEIVE JOBS";
export const FETCH_JOBS = "FETCH JOBS";
export const FILTERED_JOBS = "FILTERED JOBS";

//organizations
export const UNIQUE_ORGANIZATIONS = "UNIQUE_ORGANIZATIONS";
export const ADD_SELECTED_ORGANIZATIONS ="ADD_SELECTED_ORGANIZATIONS";
export const INCLUDE_JOB_BY_ORGANIZATION = "INCLUDE_JOB_BY_ORGANIZATION";

// job types
export const ADD_SELECTED_JOB_TYPES = "ADD_SELECTED_JOB_TYPES"
export const UNIQUE_JOB_TYPES = "UNIQUES_JOB_TYPES";
export const INCLUDE_JOB_BY_JOB_TYPE = "INCLUDE_JOB_BY_JOB_TYPE";
